spring:
  application:
    name: api-gateway
    
    
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true     
      routes:
      - id: catalog-service
        uri: http://localhost:2020
        predicates:
        - Path=/api/v1/catalogs/** 
      - id: passenger-trip-service
        uri: http://localhost:2040
        predicates:
        - Path=/api/v1/passengers/** 

          
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"  
        
server: 
  port: 8080